#name: Rest Assured API Tests
#
#on:
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main
#
#jobs:
#  api-tests:
#    runs-on: windows-latest
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#
#      - name: Set Up JDK 17
#        uses: actions/setup-java@v4
#        with:
#          distribution: 'temurin'
#          java-version: '17'
#          cache: maven
#
#      - name: Install Dependencies and Run Tests
#        run: mvn clean test
#
#


name: Java CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Use Windows runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout repository code

      - name: Set up JDK 17
        uses: actions/setup-java@v2  # Set up Java 17
        with:
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v3  # Cache Maven dependencies to speed up builds
        with:
          path: C:\Users\runneradmin\.m2\repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install -DskipTests=false  # Run Maven build

      - name: Run tests
        run: mvn test  # Run Maven tests

      - name: Upload test results
        if: always()  # Upload test results even if tests fail
        uses: actions/upload-artifact@v3  # Upload artifacts
        with:
          name: test-results
          path: target/surefire-reports  # Path to the test results folder
