#name: Rest Assured API Tests
#
#on:
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main
#
#jobs:
#  api-tests:
#    runs-on: windows-latest
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#
#      - name: Set Up JDK 17
#        uses: actions/setup-java@v4
#        with:
#          distribution: 'temurin'
#          java-version: '17'
#          cache: maven
#
#      - name: Install Dependencies and Run Tests
#        run: mvn clean test


name: Rest Assured API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  api-tests:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Install Dependencies and Run Tests
        run: mvn clean test

      - name: Upload Test Reports to GitHub Actions
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: target/surefire-reports/*.xml

      - name: Display Test Results
        run: |
          echo "Displaying test results"
          cat target/surefire-reports/*.xml
